//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterCMS.Module.Demo.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InstallGlobalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallGlobalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetterCMS.Module.Demo.Content.Resources.InstallGlobalization", typeof(InstallGlobalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating database name can contain only letters (a-z, A-Z), numbers (0-9) and underscore (_)..
        /// </summary>
        public static string CreateDatabase_DatabaseNameIsInvalid {
            get {
                return ResourceManager.GetString("CreateDatabase_DatabaseNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string.
        /// </summary>
        public static string SetupDatabase_ConnectionString {
            get {
                return ResourceManager.GetString("SetupDatabase_ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is changed. Please wait while server is reloading..
        /// </summary>
        public static string SetupDatabase_DatabaseIsOK_Reloading {
            get {
                return ResourceManager.GetString("SetupDatabase_DatabaseIsOK_Reloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        public static string SetupDatabase_DatabaseName {
            get {
                return ResourceManager.GetString("SetupDatabase_DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create database if doesn&apos;t exist.
        /// </summary>
        public static string SetupDatabase_DatabaseNameCreateNew {
            get {
                return ResourceManager.GetString("SetupDatabase_DatabaseNameCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m advanced user, let me edit connection string manually.
        /// </summary>
        public static string SetupDatabase_EditConnectionString {
            get {
                return ResourceManager.GetString("SetupDatabase_EditConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the connection information for your database..
        /// </summary>
        public static string SetupDatabase_Information {
            get {
                return ResourceManager.GetString("SetupDatabase_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated security.
        /// </summary>
        public static string SetupDatabase_IntegratedSecurity {
            get {
                return ResourceManager.GetString("SetupDatabase_IntegratedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SetupDatabase_Password {
            get {
                return ResourceManager.GetString("SetupDatabase_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SetupDatabase_Save {
            get {
                return ResourceManager.GetString("SetupDatabase_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string SetupDatabase_Server {
            get {
                return ResourceManager.GetString("SetupDatabase_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string SetupDatabase_TestConnection {
            get {
                return ResourceManager.GetString("SetupDatabase_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better CMS Database Configuration.
        /// </summary>
        public static string SetupDatabase_Title {
            get {
                return ResourceManager.GetString("SetupDatabase_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SetupDatabase_Username {
            get {
                return ResourceManager.GetString("SetupDatabase_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator roles are required, when creating new database..
        /// </summary>
        public static string TestDatabaseConnection_AdminIsRequired {
            get {
                return ResourceManager.GetString("TestDatabaseConnection_AdminIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database credentials are OK..
        /// </summary>
        public static string TestDatabaseConnection_ConnectionIsOK {
            get {
                return ResourceManager.GetString("TestDatabaseConnection_ConnectionIsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string cannot be null.
        /// </summary>
        public static string TestDatabaseConnection_ConnectionStringIsNotSet {
            get {
                return ResourceManager.GetString("TestDatabaseConnection_ConnectionStringIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name must be set.
        /// </summary>
        public static string TestDatabaseConnection_DatabaseNameIsNotSet {
            get {
                return ResourceManager.GetString("TestDatabaseConnection_DatabaseNameIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be set.
        /// </summary>
        public static string TestDatabaseConnection_PasswordIsNotSet {
            get {
                return ResourceManager.GetString("TestDatabaseConnection_PasswordIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name must be set.
        /// </summary>
        public static string TestDatabaseConnection_ServerNameIsNotSet {
            get {
                return ResourceManager.GetString("TestDatabaseConnection_ServerNameIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should be set.
        /// </summary>
        public static string TestDatabaseConnection_UserNameIsNotSet {
            get {
                return ResourceManager.GetString("TestDatabaseConnection_UserNameIsNotSet", resourceCulture);
            }
        }
    }
}
